"""OCR service layer.

Defines the `OCRService` Protocol that the orchestrator talks to, plus a
`MockOCRService` implementation that produces realistic-looking output
without requiring PaddleOCR to be installed.

Swap `MockOCRService` for a real one later by implementing the same
Protocol and passing it into `pipeline.process_document`.
"""
from __future__ import annotations

import random
from dataclasses import dataclass, field
from pathlib import Path
from typing import Protocol

import fitz  # PyMuPDF


@dataclass
class BlockResult:
    x0: float
    y0: float
    x1: float
    y1: float
    text: str
    confidence: float
    font_size_pt: float
    block_type: str = "paragraph"


@dataclass
class PageResult:
    index: int
    width_pt: float
    height_pt: float
    blocks: list[BlockResult] = field(default_factory=list)


class OCRService(Protocol):
    """Pluggable OCR contract.

    Real implementations (PaddleOCR, Tesseract, etc.) must implement
    `extract` and return a list of `PageResult` in page order.
    """

    def extract(self, source_path: Path) -> list[PageResult]: ...


# ---------------------------------------------------------------------------
# Synthetic fixture blocks (used for scanned/empty pages and image uploads)
# ---------------------------------------------------------------------------

# Multi-language sample blocks so the UI/rebuild exercises RTL + CJK +
# Devanagari paths even without a real OCR engine.
_FIXTURE_SAMPLES: list[tuple[str, str, str]] = [
    # (lang_code, block_type, text)
    ("ar", "heading", "\u062a\u0642\u0631\u064a\u0631 \u0633\u0646\u0648\u064a"),
    ("ar", "paragraph", "\u0647\u0630\u0627 \u0645\u062b\u0627\u0644 \u0644\u0646\u0635 \u0639\u0631\u0628\u064a \u064a\u062d\u0627\u0643\u064a \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u0645\u0633\u062d."),
    ("hi", "heading", "\u0935\u093e\u0930\u094d\u0937\u093f\u0915 \u0930\u093f\u092a\u094b\u0930\u094d\u091f"),
    ("hi", "paragraph", "\u092f\u0939 \u0939\u093f\u0928\u094d\u0926\u0940 \u0915\u093e \u090f\u0915 \u0928\u092e\u0942\u0928\u093e \u0935\u093e\u0915\u094d\u092f \u0939\u0948 \u091c\u094b \u0913\u0938\u0940\u0906\u0930 \u092a\u093e\u0907\u092a\u0932\u093e\u0907\u0928 \u0915\u093e \u092a\u0930\u0940\u0915\u094d\u0937\u0923 \u0915\u0930\u0924\u093e \u0939\u0948."),
    ("zh", "heading", "\u5e74\u5ea6\u62a5\u544a"),
    ("zh", "paragraph", "\u8fd9\u662f\u4e00\u4e2a\u4e2d\u6587\u6837\u672c\u6bb5\u843d\uff0c\u7528\u4e8e\u6d4b\u8bd5 OCR \u7ba1\u9053\u3002"),
    ("ja", "paragraph", "\u3053\u308c\u306f\u65e5\u672c\u8a9e\u306e\u30b5\u30f3\u30d7\u30eb\u6587\u3067\u3059\u3002"),
    ("ru", "paragraph", "\u042d\u0442\u043e \u043f\u0440\u0438\u043c\u0435\u0440 \u0442\u0435\u043a\u0441\u0442\u0430 \u043d\u0430 \u0440\u0443\u0441\u0441\u043a\u043e\u043c \u044f\u0437\u044b\u043a\u0435."),
    ("en", "paragraph", "Sample English block for the OCR mock."),
]


def _synthetic_blocks(width_pt: float, height_pt: float, *, seed: int) -> list[BlockResult]:
    """Deterministic 4-6 block fixture split into header/body/footer zones."""
    rng = random.Random(seed)
    margin = 40.0
    usable_w = width_pt - 2 * margin
    blocks: list[BlockResult] = []

    # Heading at the top
    blocks.append(
        BlockResult(
            x0=margin,
            y0=margin,
            x1=margin + usable_w,
            y1=margin + 30,
            text=_FIXTURE_SAMPLES[0][2],
            confidence=round(rng.uniform(0.78, 0.85), 2),
            font_size_pt=18.0,
            block_type="heading",
        )
    )

    # Body paragraphs (3-4)
    y = margin + 60
    body_samples = [s for s in _FIXTURE_SAMPLES if s[1] == "paragraph"]
    rng.shuffle(body_samples)
    for _, _, text in body_samples[: rng.randint(3, 4)]:
        h = 40.0 + rng.uniform(0, 20)
        if y + h > height_pt - margin - 30:
            break
        blocks.append(
            BlockResult(
                x0=margin,
                y0=y,
                x1=margin + usable_w,
                y1=y + h,
                text=text,
                confidence=round(rng.uniform(0.70, 0.88), 2),
                font_size_pt=11.0,
                block_type="paragraph",
            )
        )
        y += h + 20

    # Footer line
    blocks.append(
        BlockResult(
            x0=margin,
            y0=height_pt - margin - 14,
            x1=margin + usable_w,
            y1=height_pt - margin,
            text="Page footer - generated by MockOCRService",
            confidence=round(rng.uniform(0.72, 0.80), 2),
            font_size_pt=9.0,
            block_type="paragraph",
        )
    )
    return blocks


# ---------------------------------------------------------------------------
# Native-text extraction (used when the input PDF has a real text layer)
# ---------------------------------------------------------------------------


def _native_blocks(page: "fitz.Page") -> list[BlockResult]:
    """Translate PyMuPDF `get_text('dict')` output into BlockResult rows.

    This is still considered a "mock" because we pretend PaddleOCR produced
    it - but the data is real so demos against digital PDFs look great.
    """
    blocks: list[BlockResult] = []
    data = page.get_text("dict")
    for raw in data.get("blocks", []):
        if raw.get("type") != 0:
            # Type 1 = image block, skip.
            continue
        # Collect paragraph-level text and the average font size.
        lines = raw.get("lines") or []
        if not lines:
            continue
        text_parts: list[str] = []
        sizes: list[float] = []
        for line in lines:
            line_parts: list[str] = []
            for span in line.get("spans", []):
                span_text = span.get("text") or ""
                if span_text.strip():
                    line_parts.append(span_text)
                    sizes.append(float(span.get("size") or 11.0))
            if line_parts:
                text_parts.append("".join(line_parts))
        text = "\n".join(t.strip() for t in text_parts if t.strip())
        if not text:
            continue
        x0, y0, x1, y1 = raw.get("bbox", (0, 0, 0, 0))
        avg_size = sum(sizes) / len(sizes) if sizes else 11.0
        # Rough heading heuristic: short single line with larger font.
        is_heading = len(lines) == 1 and avg_size >= 14.0 and len(text) <= 120
        blocks.append(
            BlockResult(
                x0=float(x0),
                y0=float(y0),
                x1=float(x1),
                y1=float(y1),
                text=text,
                confidence=round(random.uniform(0.94, 0.99), 2),
                font_size_pt=avg_size,
                block_type="heading" if is_heading else "paragraph",
            )
        )
    return blocks


# ---------------------------------------------------------------------------
# Mock service implementation
# ---------------------------------------------------------------------------


class MockOCRService:
    """Smart mock OCR service.

    - For native PDFs, returns real `page.get_text('dict')` data dressed up
      with a plausible confidence score. Demos look convincing on any
      real PDF the user uploads.
    - For scanned pages (no text layer) or image uploads, returns a
      deterministic multilingual fixture block set so the UI still has
      something to render.
    - Supports both PDF and single-image inputs. Images are wrapped in a
      one-page PDF-sized "canvas" internally.

    Swap me for a real PaddleOCR backed class later; the Protocol
    signature is what matters, not my internals.
    """

    IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".webp", ".bmp", ".tif", ".tiff"}
    # US Letter-ish defaults for image-only uploads (in PDF points).
    DEFAULT_IMAGE_PAGE_WIDTH = 612.0
    DEFAULT_IMAGE_PAGE_HEIGHT = 792.0

    def extract(self, source_path: Path) -> list[PageResult]:
        source_path = Path(source_path)
        suffix = source_path.suffix.lower()
        if suffix in self.IMAGE_SUFFIXES:
            return self._extract_image(source_path)
        return self._extract_pdf(source_path)

    def _extract_pdf(self, pdf_path: Path) -> list[PageResult]:
        results: list[PageResult] = []
        with fitz.open(pdf_path) as doc:
            for idx, page in enumerate(doc):
                width = float(page.rect.width)
                height = float(page.rect.height)
                native = _native_blocks(page)
                if native:
                    blocks = native
                else:
                    blocks = _synthetic_blocks(width, height, seed=idx)
                results.append(
                    PageResult(
                        index=idx,
                        width_pt=width,
                        height_pt=height,
                        blocks=blocks,
                    )
                )
        return results

    def _extract_image(self, image_path: Path) -> list[PageResult]:
        # We don't actually OCR the image - we just produce a single-page
        # synthetic fixture the size of a Letter page so the rest of the
        # pipeline has something to work with.
        width = self.DEFAULT_IMAGE_PAGE_WIDTH
        height = self.DEFAULT_IMAGE_PAGE_HEIGHT
        blocks = _synthetic_blocks(width, height, seed=1)
        return [PageResult(index=0, width_pt=width, height_pt=height, blocks=blocks)]
