# Generated by Django 4.2.30 on 2026-04-17 06:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='originals/')),
                ('translated_file', models.FileField(blank=True, null=True, upload_to='translated/')),
                ('source_lang', models.CharField(default='auto', max_length=10)),
                ('target_lang', models.CharField(default='en', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('width_pt', models.FloatField()),
                ('height_pt', models.FloatField()),
                ('preview', models.ImageField(blank=True, null=True, upload_to='previews/')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='engine.document')),
            ],
            options={
                'ordering': ('document_id', 'index'),
                'unique_together': {('document', 'index')},
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('block_type', models.CharField(choices=[('paragraph', 'Paragraph'), ('heading', 'Heading'), ('list', 'List'), ('table_cell', 'Table cell')], default='paragraph', max_length=20)),
                ('x0', models.FloatField()),
                ('y0', models.FloatField()),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField(blank=True, default='')),
                ('detected_lang', models.CharField(blank=True, default='', max_length=16)),
                ('confidence', models.FloatField(default=0.0)),
                ('font_size_pt', models.FloatField(default=11.0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='engine.page')),
            ],
            options={
                'ordering': ('page_id', 'order'),
            },
        ),
    ]
